### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jamesshenry** [agc93/spectre.cli.extensions.dependencyinjection#7]
Not an issue but why not use Microsoft's ConfigurationBuilder & default service container?

**Comment by agc93** [comment]
`ConfigurationBuilder` specifically would require bringing `Microsoft.Extensions.Configuration` in as a dependency, which I'd like to avoid given this isn't a config-focussed library.

As for the container, what do you mean by the "default service container"? The registrar just accepts any `IServiceCollection` implementation that's passed to it.
